package nl.humanitas.model.psychosomatisch;

public enum Ziektebeeld {
	ADHD,
	ANGSTSTOORNISSEN,
	AUTISME,
	BIPOLAR_STOORNIS,
	DELICT_GEDRAG,
	DELIER,
	DEMENTIE,
	DEPRESSIE,
	DWANGSTOORNIS,
	EETSTOORNISSEN,
	GEDRAGSTOORNISSEN,
	PERSOONLIJKHEIDSPROBLEMATIEK,
	POSTTRAUMATISCH_STRESSSTOORNIS,
	PSYCHOSE_EN_SCHIZOFRENIE,
	SOMATISCH_ONVOLDOENDE_VERKLAARDE_LICHAMELIJKE_KLACHTEN,
	VERSLAVING
}
